name = "r2-proxy"
main = "r2-proxy.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "merrychristmas"

# 配置你的自定义域名路由
# routes = [
#   { pattern = "r2-api.your-domain.com/*", zone_name = "your-domain.com" }
# ]
